
export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const CONNECT = 'CONNECT';
export type CONNECT = typeof CONNECT;

export const DISCONNECT = 'DISCONNECT';
export type DISCONNECT = typeof DISCONNECT;

